sudo: false
language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
script:
  - |
      CXXFLAGS="-Wall -Wextra -Wpedantic -Werror" \
        CFLAGS="-Wall -Wextra -Wpedantic -Werror" cmake .
  - make -j 4
  - ./ithitest
